version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: faxnologs_db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: admin!@#123
    volumes:
      - type: bind
        source: c:/faxnologs/data
        target: /var/opt/mssql/data
    networks:
      faxnologs_network:
    ports:
      - 1433:1433

  faxnologs_webapp:
    image: kparginos/faxnologswebapp:1.3.0
    restart: always
    container_name: faxnologs_webapp
    networks:
      - faxnologs_network
    ports:
      - 6001:80

networks:
  faxnologs_network:
